### ISSUE TITLE
Issues with gensim, matchms, ms2deepscore and spec2vec libraries

### ISSUE THREAD

**Issue by RemyMG** [mandelbrot-project/spectral_lib_matcher#19]
I encountered several issues when trying to run spectral_lib_matcher.

1. First when I tried to create spectral_lib_matcher environment. As matchms seems not to work under Python >3.10 you should specify it in environment.yml otherwise it gives an error message.

2. Then I had to `pip install --upgrade` manually all the following libraries: `matchms`, `ms2deepscore` and `spec2vec`

3. When all the libraries were manually installed the following code chunk was finally running: `python src/processor.py -v -o data/annotations.tsv -p 0.01 -m 0.01 -s 0.2 -k 6 -z ModifiedCosine data/query.mgf data/spectral_lib.mgf `

How to create the environment in one step? Since I tried to modify the environment.yml file but it didn't work either.

Thank you for your help.

Some of the errors I encountered:

`(base) PS C:\Users\marcellr\GitHub\spectral_lib_matcher> conda activate spectral_lib_matcher`
`(spectral_lib_matcher) PS C:\Users\marcellr\GitHub\spectral_lib_matcher> python src/processor.py -v -o data/annotations.tsv -p 0.01 -m 0.01 -s 0.2 -k 6 -z ModifiedCosine data/query.mgf data/spectral_lib.mgf`

1. First error message:
`Traceback (most recent call last):
  File "C:\Users\marcellr\GitHub\spectral_lib_matcher\src\processor.py", line 7, in <module>
    from mandelbrot_spectral_lib_matcher.binary import read_binary_database
  File "C:\Users\marcellr\GitHub\spectral_lib_matcher\src\mandelbrot_spectral_lib_matcher\__init__.py", line 1, in <module>
    from . import processor
  File "C:\Users\marcellr\GitHub\spectral_lib_matcher\src\mandelbrot_spectral_lib_matcher\processor.py", line 1, in <module>
    import gensim
ModuleNotFoundError: No module named 'gensim'`
Solved by installing gensim:
`(spectral_lib_matcher) PS C:\Users\marcellr\GitHub\spectral_lib_matcher> pip install --upgrade gensim`
`Collecting gensim
  Using cached gensim-4.2.0-cp39-cp39-win_amd64.whl (23.9 MB)
Collecting smart-open>=1.8.1
  Using cached smart_open-6.2.0-py3-none-any.whl (58 kB)
Collecting Cython==0.29.28
  Using cached Cython-0.29.28-py2.py3-none-any.whl (983 kB)
Requirement already satisfied: numpy>=1.17.0 in c:\users\marcellr\anaconda3\envs\spectral_lib_matcher\lib\site-packages (from gensim) (1.20.3)
Requirement already satisfied: scipy>=0.18.1 in c:\users\marcellr\anaconda3\envs\spectral_lib_matcher\lib\site-packages (from gensim) (1.7.3)
Installing collected packages: smart-open, Cython, gensim
Successfully installed Cython-0.29.28 gensim-4.2.0 smart-open-6.2.0`

2. Second error message: 
`(spectral_lib_matcher) PS C:\Users\marcellr\GitHub\spectral_lib_matcher> python src/processor.py -v -o data/annotations.tsv -p 0.01 -m 0.01 -s 0.2 -k 6 -z ModifiedCosine data/query.mgf data/spectral_lib.mgf`

`Traceback (most recent call last):
  File "C:\Users\marcellr\GitHub\spectral_lib_matcher\src\processor.py", line 7, in <module>
    from mandelbrot_spectral_lib_matcher.binary import read_binary_database
  File "C:\Users\marcellr\GitHub\spectral_lib_matcher\src\mandelbrot_spectral_lib_matcher\__init__.py", line 1, in <module>
    from . import processor
  File "C:\Users\marcellr\GitHub\spectral_lib_matcher\src\mandelbrot_spectral_lib_matcher\processor.py", line 13, in <module>
    from matchms.similarity import NeutralLossesCosine
ImportError: cannot import name 'NeutralLossesCosine' from 'matchms.similarity' (C:\Users\marcellr\Anaconda3\envs\spectral_lib_matcher\lib\site-packages\matchms\similarity\__init__.py)`

**Comment by ArnaudGaudry** [comment]
It should be ok now! Try to uninstall the environment and then reinstall everything :)
