### ISSUE TITLE
calculate_scores() got an unexpected keyword argument 'array_type'

### ISSUE THREAD

**Issue by RemyMG** [mandelbrot-project/spectral_lib_matcher#20]
Hello,

Since the recent update, spectral_lib_matcher displays several errors: 

-  as `matchms >= 0.18.0` is not on bioconda yet, `conda env create -f environment.yml` ends with an error message. `matchms` is stuck to `0.17.0` on bioconda.

-  when running `python src/processor.py -v -o data/annotations.tsv -p 0.01 -m 0.01 -s 0.2 -k 6 -z ModifiedCosine data/query.mgf data/spectral_lib.mgf ` it gives `calculate_scores() got an unexpected keyword argument 'array_type'`

here is the complete error message:
`Your query spectra will be matched against the 221 spectra of the spectral library.
Processing
Traceback (most recent call last):
  File "C:\Users\marcellr\GitHub\spectral_lib_matcher\src\processor.py", line 177, in <module>
    processor(log, config)
  File "C:\Users\marcellr\GitHub\spectral_lib_matcher\src\processor.py", line 108, in processor
    df = process(query, database, config.parent_mz_tolerance, config.msms_mz_tolerance, config.min_score,
  File "C:\Users\marcellr\GitHub\spectral_lib_matcher\src\mandelbrot_spectral_lib_matcher\processor.py", line 51, in process
    scores = calculate_scores(references=spectra_query, queries=spectra_db, array_type="numpy",is_symmetric=False, similarity_function=similarity_score)
TypeError: calculate_scores() got an unexpected keyword argument 'array_type'`

I get this message whatever the `matchms` version (`0.17.0` or `0.18.0` I installed with `pip install`)

**Comment by RemyMG** [comment]
It finally works, after uninstalling and re-installing & **upgrading** all the packages. You can find here packages versioning: [spectral_lib_matcher pckg versions.txt](https://github.com/mandelbrot-project/spectral_lib_matcher/files/10426252/spectral_lib_matcher.pckg.versions.txt)

**Comment by Adafede** [comment]
Hi @RemyMG, thank you for reporting! I am actually not fixing this because I know from matchms developer that he will soon release new versions making all the dependencies compatible...hope this is OK for now, else just let me know

**Comment by Adafede** [comment]
Hi again @RemyMG , with 5c6a41e82d91ee92a9557b51a5523addea42e164 should now be fixed! Do not hesitate to let us know if this is not the case!
