### ISSUE TITLE
"-z Cosine"  error: name 'Cosine' is not defined

### ISSUE THREAD

**Issue by YUANMY2021** [mandelbrot-project/spectral_lib_matcher#21]
what are the other method's exact name

If  I want to batch match them using not the default"Matched Cosine" function, but the "Cosine"

<img width="282" alt="image" src="https://user-images.githubusercontent.com/79961133/219546483-2ec6f5bf-2f58-4c72-b264-08d0e55589bb.png">
<img width="113" alt="image" src="https://user-images.githubusercontent.com/79961133/219546502-42c52ed6-1176-4f27-8690-eaf253e60de1.png">

**Comment by Adafede** [comment]
Hi @YUANMY2021,

You are right, this part was not documented. It is now, see: a7018e88b85aa31de8f7fdc50692203032aeb82a

More specifically, I guess that what you are looking for is `CosineHungarian`

**Comment by Adafede** [comment]
@YUANMY2021 could you get what you wanted?

**Comment by Adafede** [comment]
closing as no reaction, feel free to reopen
